name: Check images digest for multi-arch

on:
  pull_request:
    paths:
      - '**[dD]ockerfile**'
      - '.github/workflow/digestcheck.yaml'
      - 'contrib/digestcheck.sh'
      - '!**vendor**'

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Install crane
      env:
        VERSION: "v0.15.2"
      run: |
        curl -sL "https://github.com/google/go-containerregistry/releases/download/$VERSION/go-containerregistry_Linux_x86_64.tar.gz" > go-containerregistry.tar.gz
        tar -zxvf go-containerregistry.tar.gz -C /usr/local/bin/ crane
      
    - name: Check digests
      env:
        TERM: xterm-color
      run: ./contrib/digestcheck.sh ${{ github.workspace }}
