name: vmtests
on:
  pull_request:
    paths-ignore:
      - 'docs/**'
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'

jobs:
  build:
    name: Build tetragon
    runs-on: ubuntu-latest
    timeout-minutes: 20
    concurrency:
      group: ${{ github.ref }}-vmtest-build
      cancel-in-progress: true
    steps:
    - name: Install Go
      uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
      with:
        # renovate: datasource=golang-version depName=go
        go-version: '1.21.1'

    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        path: go/src/github.com/cilium/tetragon/

    - name: Install build dependencies
      run: |
        sudo apt install libelf-dev netcat-traditional libcap-dev gcc
        echo `which clang`
        echo `which llc`
        echo `clang --version`
    - name: Build
      env:
        GOPATH: /home/runner/work/tetragon/tetragon/go
      run: |
        cd go/src/github.com/cilium/tetragon/
        make tetragon-bpf tester-progs test-compile
        make -C tests/vmtests

    - name: Split tests
      run: |
        #  see testfile below
        cd go/src/github.com/cilium/tetragon/
        go run ./tools/split-tetragon-gotests -ci-run 1

    - name: tar build
      run: |
        cd go/src/github.com/cilium/
        tar cz --exclude='tetragon/.git' -f /tmp/tetragon.tar ./tetragon

    - name: upload build
      uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4
      with:
         name: tetragon-build
         path: /tmp/tetragon.tar
         retention-days: 5
  test:
    strategy:
        fail-fast: false
        matrix:
           kernel:
              # renovate: datasource=docker depName=quay.io/lvh-images/kernel-images
              - 'bpf-next-20230927.012631'
              # renovate: datasource=docker depName=quay.io/lvh-images/kernel-images
              - '5.15-20230922.193656'
              # renovate: datasource=docker depName=quay.io/lvh-images/kernel-images
              - '5.10-20230922.193656'
              # renovate: datasource=docker depName=quay.io/lvh-images/kernel-images
              - '5.4-20230922.193656'
              # renovate: datasource=docker depName=quay.io/lvh-images/kernel-images
              - '4.19-20230922.193656'
           group:
              - 0
    concurrency:
      group: ${{ github.ref }}-vmtest-${{ matrix.kernel }}-${{ matrix.group }}
      cancel-in-progress: true
    needs: build
    name: Test kernel ${{ matrix.kernel }} / test group ${{ matrix.group }}
    runs-on: ubuntu-latest-4cores-16gb
    timeout-minutes: 60
    steps:
    - name: Install VM test dependencies
      run: |
        sudo apt-get -qy update
        sudo apt-cache search qemu
        sudo apt-get -qy install mmdebstrap libguestfs-tools qemu-utils qemu-system-x86 cpu-checker qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils virtinst virt-manager

    - name: Make kernel accessible
      run: |
        sudo chmod go+rX -R /boot/

    - name: download build data
      uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
      with:
         name: tetragon-build

    - name: extract build data
      # NB: currently, due to how tests work, we need to extract to the same path.
      run: |
        mkdir -p go/src/github.com/cilium/
        tar xf tetragon.tar -C go/src/github.com/cilium

    - name: test kernel ${{ matrix.kernel }}
      if: ${{ !startsWith(matrix.kernel, '4.19') }}
      run: |
        cd go/src/github.com/cilium/tetragon
        ./tests/vmtests/fetch-data.sh ${{ matrix.kernel }}
        kimage=$(find tests/vmtests/test-data/kernels -path "*vmlinuz*" -type f)
        echo "Using: kernel:$kimage"
        sudo ./tests/vmtests/tetragon-vmtests-run \
                --kernel ${kimage} \
                --kernel-ver  ${{ matrix.kernel }} \
                --base tests/vmtests/test-data/images/base.qcow2 \
                --testsfile ./tests/vmtests/test-group-${{ matrix.group }}

    - name: test kernel ${{ matrix.kernel }} with btf file
      if: ${{ startsWith(matrix.kernel, '4.19') }}
      run: |
        cd go/src/github.com/cilium/tetragon
        ./tests/vmtests/fetch-data.sh ${{ matrix.kernel }}
        kimage=$(find tests/vmtests/test-data/kernels -path "*vmlinuz*" -type f)
        btf=$(find tests/vmtests/test-data/kernels -path "*btf*" -type f)
        echo "Using: kernel:$kimage bptf:$btf"
        sudo ./tests/vmtests/tetragon-vmtests-run \
                --kernel ${kimage} \
                --kernel-ver  ${{ matrix.kernel }} \
                --btf-file ${btf} \
                --base tests/vmtests/test-data/images/base.qcow2 \
                --testsfile ./tests/vmtests/test-group-${{ matrix.group }}

    - name: Chmod test results on failure or cancelation
      if: failure() || cancelled()
      run: |
        sudo chmod -R go+rX go/src/github.com/cilium/tetragon/tests/vmtests/vmtests-results-*

    - name: Upload test results on failure or cancelation
      if: failure() || cancelled()
      uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
      with:
        name: tetragon-vmtests-${{ matrix.kernel }}-${{ matrix.group }}-results
        path: go/src/github.com/cilium/tetragon/tests/vmtests/vmtests-results-*
        retention-days: 5
  post-test:
    runs-on: ubuntu-latest
    needs: [test]
    if: success()
    steps:
    - name: Create truncated build file
      run: |
        touch /tmp/tetragon.tar
    - name: Upload truncated file
      uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4
      with:
         name: tetragon-build
         path: /tmp/tetragon.tar
         retention-days: 1
